[build]
  command = "npm run build"
  publish = "/build"
  base = "/"

[[redirects]]
# index.html
  from = "/index.html"
  to = "/"
  status = 301      # (default): Permanent redirect
  force = true      # redirect even if matching file found

[[redirects]]
# no hit
  from = "/*"
  to = "/"
  status = 301      # (default): Permanent redirect
  force = true     # redirect only if actual ressource does not exist

# very good example
# https://docs.netlify.com/configure-builds/file-based-configuration/